### ISSUE TITLE
Reason why use `raw-loader`

### ISSUE THREAD

**Issue by geoseong** [visualkhh/simple-boot-front#1]
Hello,

I'm studying this framework starting with webpack example.

I just want to know why you used [`raw-loader`](https://v4.webpack.js.org/loaders/raw-loader/) in webpack example.

I found stylesheet loading problem when I...
1. when import css file without using `raw-loader` and configuring configuring `css-loader` & `style-loader` in [`webpack.config.js`](https://github.com/visualkhh/simple-boot-front/blob/39ed827b85/examples/webpack/webpack.config.js) -> **error in browser**
    - [examples/webpack/webpack.config.js](https://github.com/visualkhh/simple-boot-front/blob/39ed827b85/examples/webpack/webpack.config.js)
    ```js
    {
      test: /\.css$/i,
      use: ['style-loader', 'css-loader'],
    },
    ```
    - [examples/webpack/src/app/layouts/App.ts#L6-L7](https://github.com/visualkhh/simple-boot-front/blob/39ed827b85/examples/webpack/src/app/layouts/App.ts#L6-L7)
    ```ts
    import bootstrap from '../../assets/libs/bootstrap/css/bootstrap.min.css';
    import css from './dashboard.css'
    ```
    - **error** in browser
    ```
    Uncaught TypeError: it.replace is not a function
        at Module.js:183
        at Array.map (<anonymous>)
        at App.Module.transStyle (Module.js:180)
        at App.Module.render (Module.js:170)
        at SimProxyMethodHandler.set (SimProxyMethodHandler.js:47)
        at Proxy.Module._onInit (Module.js:75)
        at SimpleApplication.renderRouterModule (SimpleApplication.js:111)
        at SimpleApplication.js:74
        at Array.forEach (<anonymous>)
        at SimpleApplication.executeRouter (SimpleApplication.js:72)
    ```
    - this can be fixed put this code before [src/module/Module.ts#L167](https://github.com/visualkhh/simple-boot-front/blob/39ed827b851bd35e7b164cf906ccf71946a0c0de/src/module/Module.ts#L167)
    ```ts
    if (typeof it === 'object') return '';
    ```
    - but style contains `/*[module-selector]*/` (styleImports) is not loaded

1. configuring `css-loader` & `style-loader` in [`webpack.config.js`](https://github.com/visualkhh/simple-boot-front/blob/39ed827b85/examples/webpack/webpack.config.js) -> **stylesheet not loaded**

    ```js
    {
      test: /\.css$/i,
      use: ['style-loader', 'css-loader'],
    },
    ```

    - **to fix**: add `!!` in front of path. refer to following [webpack raw-loader example](https://v4.webpack.js.org/loaders/raw-loader/#inline)
    ```ts
    import bootstrap from '!!raw-loader!../../assets/libs/bootstrap/css/bootstrap.min.css';
    import css from '!!raw-loader!./dashboard.css'
    ```

    - but style contains `/*[module-selector]*/` (styleImports) is not loaded

so that's why you use `raw-loader` to solve this problem?

### Logs in `Module.ts`
I put `console.log`s in **node_modules/simple-boot-front/module/Module.js** and put hotfix code
```js
    Module.prototype.transStyle = function (selector) {
        console.log('debug: this.styleImports', this.styleImports)
        console.log('debug', { selector })

        var _a;
        var join = (_a = this.styleImports) === null || _a === void 0 ? void 0 : _a.map(function (it) {
            // eslint-disable-next-line prefer-regex-literals
            var regExp = new RegExp('\\/\\*\\[module\\-selector\\]\\*\\/', 'gi'); // 생성자
            if (typeof it === 'object') return ''; // <- I put hotfix when using `css-loader`&`style-loader` without `raw-loader`
            return it.replace(regExp, '#' + selector + ' ');
        }).join(' ');
        Renderer.prependStyle(selector, join);
    };
```
- `css-loader` and `style-loader` instead of using `raw-loader`
![image](https://user-images.githubusercontent.com/19166187/114297220-58eec580-9aea-11eb-94bd-a1921d42ca31.png)

- using `raw-loader`
![image](https://user-images.githubusercontent.com/19166187/114297238-758afd80-9aea-11eb-8983-dd5eba8c286d.png)

if it is right, you can (or I) post this content somewhere for those who want to study this.

thanks

**Comment by visualkhh** [comment]
For flexible handling of css, html content in the framework,
raw data file contents had to be imported and processed.

Therefore, raw-loader was used.

--------
The problem above is...
Css, html, and style loader in "webpack" seem to have unexpected errors.
