### ISSUE TITLE
VSCode configuration file related to "sort-imports" extension

### ISSUE THREAD

**Issue by geoseong** [visualkhh/simple-boot-front#12]
@visualkhh please consider VSCode's config file (.vscode/settings.json) newly created

I described the reason [here](https://github.com/visualkhh/simple-boot-front/commit/989aa8302a01a9a72410f2ff88af95ee06f7f55d#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357).

please check this out.

**Comment by visualkhh** [comment]
I checked. Thank you.
Added ".vcode" in ".gitignore".
You can use ".vcode" additionally in your local stage

**Comment by geoseong** [comment]
ok, thanks
